version: '3'
services:
  backend:
    build: ./backend
    container_name: app-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/data:/app/data
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=development
    
  frontend:
    build: ./frontend
    container_name: app-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend